### ISSUE TITLE
Privacy audits

### ISSUE THREAD

**Issue by ghost** [joomla/cross-cms-compliance#1]

**Comment by ghost** [comment]
Remember to look at plugin/module/extension guidelines and project coding standards; universal privacy principles; and project/code specific data issues.

**Comment by jeckodevelopment** [comment]
sometimes, coding standards are not clear / easy to find / published.

**Comment by ghost** [comment]
Have set up a Project for this: https://github.com/joomla/cross-cms-compliance/projects/1
